---
apiVersion: v1
kind: Service
metadata:
  name: rs-tcp-clusterip
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: rs-tcp-0
  ports:
    - protocol: TCP
      port: 7400
      targetPort: 7400
  externalIPs:
    - 10.15.74.53
